<a href="https://colab.research.google.com/github/faridelya/Pandas-Seaborn-Numpy/blob/main/A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving mdc.csv to mdc.csv

In [ ]:
import io
import pandas as pd
pd.set_option('display.max_rows', 5000)
pd.set_option('display.max_columns', 500)

In [ ]:

df = pd.read_csv(io.BytesIO(uploaded['mdc.csv']), encoding='latin-1')
df

,Unnamed: 0,title,year,genre,runtime,mpa_rating,imdb_rating,imdb_votes,imdb_gross,director,stars,description,crit_consensus,tomato_meter,tomato_review,tom_aud_score,tom_ratings,entity,id
0,1,Captain America,1944,"Action, Adventure, Sci-Fi",244,Approved,5.5,844,0,Elmer Clifton,"Elmer Clifton,Dick Purcell,Lorna Gray,Lionel A...",Superhero Captain America battles the evil for...,"Find one of these old serials, friend. They're...",0,1,82,250,MARVEL,1
1,2,Howard the Duck,1986,"Action, Adventure, Comedy",110,PG,4.7,44073,16300000,Willard Huyck,"Willard Huyck,Lea Thompson,Jeffrey Jones,Tim R...",A sarcastic humanoid duck is pulled from his h...,"While it has its moments, Howard the Duck suff...",13,78,38,50000,MARVEL,2
2,3,Blade,1998,"Action, Horror, Sci-Fi",120,R,7.1,251243,70090000,Stephen Norrington,"Stephen Norrington,Wesley Snipes,Stephen Dorff...","A half-vampire, half-mortal man becomes a prot...","Though some may find the plot a bit lacking, B...",55,103,78,250000,MARVEL,3
3,4,X-Men,2000,"Action, Adventure, Sci-Fi",104,PG-13,7.4,580354,157300000,Bryan Singer,"Bryan Singer,Patrick Stewart,Hugh Jackman,Ian ...",In a world where mutants (evolved super-powere...,"Faithful to the comics and filled with action,...",82,174,83,250000,MARVEL,4
4,5,Blade II,2002,"Action, Fantasy, Horror",117,R,6.7,203813,82350000,Guillermo del Toro,"Guillermo del Toro,Wesley Snipes,Kris Kristoff...",Blade forms an uneasy alliance with the vampir...,Though Blade II offers more of what worked in ...,57,150,68,250000,MARVEL,5
5,6,Spider-Man,2002,"Action, Adventure, Sci-Fi",121,PG-13,7.3,702986,403710000,Sam Raimi,"Sam Raimi,Tobey Maguire,Kirsten Dunst,Willem D...","When bitten by a genetically modified spider, ...",Not only does Spider-Man provide a good dose o...,90,244,67,250000,MARVEL,6
6,7,Daredevil,2003,"Action, Crime",103,PG-13,5.3,208847,102540000,Mark Steven Johnson,"Mark Steven Johnson,Ben Affleck,Jennifer Garne...",A man blinded by toxic waste which also enhanc...,While Ben Affleck fits the role and the story ...,44,229,35,250000,MARVEL,7
7,8,X2: X-Men United,2003,"Action, Sci-Fi, Thriller",134,PG-13,7.4,519747,214950000,Bryan Singer,"Bryan Singer,Patrick Stewart,Hugh Jackman,Hall...",When anti-mutant Colonel William Stryker kidna...,"Tightly scripted, solidly acted, and impressiv...",85,246,85,250000,MARVEL,8
8,9,Hulk,2003,"Action, Sci-Fi",138,PG-13,5.6,255002,132180000,Ang Lee,"Ang Lee,Eric Bana,Jennifer Connelly,Sam Elliot...","Bruce Banner, a genetics researcher with a tra...",While Ang Lee's ambitious film earns marks for...,62,237,29,250000,MARVEL,9
9,10,The Punisher,2004,"Action, Crime, Drama",124,R,6.4,151872,33680000,Jonathan Hensleigh,"Jonathan Hensleigh,Thomas Jane,John Travolta,S...",An undercover FBI agent becomes a vigilante an...,A good cast fails to elevate this overly viole...,28,172,63,250000,MARVEL,10
10,11,Spider-Man 2,2004,"Action, Adventure, Sci-Fi",127,PG-13,7.3,556980,373590000,Sam Raimi,"Sam Raimi,Tobey Maguire,Kirsten Dunst,Alfred M...",Peter Parker is beset with troubles in his fai...,Boasting an entertaining villain and deeper em...,93,274,82,250000,MARVEL,11
11,12,Blade: Trinity,2004,"Action, Adventure, Fantasy",113,R,5.8,168363,52410000,David S. Goyer,"David S. Goyer,Wesley Snipes,Kris Kristofferso...","Blade, now a wanted man by the FBI, must join ...","Louder, campier, and more incoherent than its ...",25,168,58,250000,MARVEL,12
12,13,Elektra,2005,"Action, Adventure, Crime",97,PG-13,4.7,88518,24410000,Rob Bowman,"Rob Bowman,Jennifer Garner,Goran Visnjic,Will ...",Elektra the warrior survives a near-death expe...,Jennifer Garner inhabits her role with earnest...,11,166,29,250000,MARVEL,13
13,14,Fantastic Four,2005,"Action, Adventure, Fantasy",106,PG-13,5.7,315297,154700000,Tim Story,"Tim Story,Ioan Gruffudd,Michael Chiklis,Chris ...",A group of astronauts gain superpowers after a...,"Marred by goofy attempts at wit, subpar acting...",27,214,45,250000,MARVEL,14
14,15,X-Men: The Last Stand,2006,"Action, Adventure, Sci-Fi",104,PG-13,6.7,490269,234360000,Brett Ratner,"Brett Ratner,Patrick Stewart,Hugh Jackman,Hall...",The human government develops a cure for mutat...,X-Men: The Last Stand provides plenty of mutan...,57,240,61,250000,MARVEL,15
15,16,Ghost Rider,2007,"Action, Fantasy, Thriller",110,PG-13,5.3,226797,115800000,Mark Steven Johnson,"Mark Steven Johnson,Nicolas Cage,Eva Mendes,Sa...",When motorcycle rider Johnny Blaze sells his s...,"Ghost Rider is a sour mix of morose, glum hist...",26,141,48,250000,MARVEL,16
16,17,Spider-Man 3,2007,"Action, Adventure, Sci-Fi",139,PG-13,6.2,510723,336530000,Sam Raimi,"Sam Raimi,Tobey Maguire,Kirsten Dunst,Topher G...",A strange black entity from another world bond...,Though there are more characters and plotlines...,63,262,51,250000,MARVEL,17
17,18,Fantastic Four: Rise of the Silver Surfer,2007,"Action, Adventure, Fantasy",92,PG,5.6,253897,131920000,Tim Story,"Tim Story,Ioan Gruffudd,Jessica Alba,Chris Eva...",The Fantastic Four learn that they aren't the ...,"While an improvement on its predecessor, Fanta...",37,171,51,250000,MARVEL,18
18,19,Iron Man,2008,"Action, Adventure, Sci-Fi",126,PG-13,7.9,964114,318410000,Jon Favreau,"Jon Favreau,Robert Downey Jr.,Gwyneth Paltrow,...","After being held captive in an Afghan cave, bi...","Powered by Robert Downey Jr.'s vibrant charm, ...",94,281,91,250000,MARVEL,19
19,20,The Incredible Hulk,2008,"Action, Adventure, Sci-Fi",112,PG-13,6.7,445822,134520000,Louis Leterrier,"Louis Leterrier,Edward Norton,Liv Tyler,Tim Ro...","Bruce Banner, a scientist on the run from the ...",The Incredible Hulk may not be quite the smash...,67,238,70,250000,MARVEL,20
20,21,Punisher: War Zone,2008,"Action, Crime, Drama",103,R,5.9,60767,7950000,Lexi Alexander,"Lexi Alexander,Ray Stevenson,Dominic West,Juli...","Frank Castle, known as the Punisher, ruthlessl...",Punisher: War Zone recalls the excessively vio...,29,111,42,100000,MARVEL,21
21,22,X-Men Origins: Wolverine,2009,"Action, Sci-Fi",107,PG-13,6.6,475561,179880000,Gavin Hood,"Gavin Hood,Hugh Jackman,Liev Schreiber,Ryan Re...","The early years of James Logan, featuring his ...","Though Hugh Jackman gives his all, he can't he...",37,263,58,250000,MARVEL,22
22,23,Iron Man 2,2010,"Action, Adventure, Sci-Fi",124,PG-13,7.0,742416,312430000,Jon Favreau,"Jon Favreau,Robert Downey Jr.,Mickey Rourke,Gw...",With the world now aware of his identity as Ir...,It isn't quite the breath of fresh air that Ir...,72,304,71,250000,MARVEL,23
23,24,Thor,2011,"Action, Adventure, Fantasy",115,PG-13,7.0,767687,181030000,Kenneth Branagh,"Kenneth Branagh,Chris Hemsworth,Anthony Hopkin...",The powerful but arrogant god Thor is cast out...,A dazzling blockbuster that tempers its sweepi...,77,291,76,100000,MARVEL,24
24,25,X: First Class,2011,"Action, Adventure, Sci-Fi",131,PG-13,7.7,655399,146410000,Matthew Vaughn,"Matthew Vaughn,James McAvoy,Michael Fassbender...","In the 1960s, superpowered humans Charles Xavi...","With a strong script, stylish direction, and p...",86,298,87,100000,MARVEL,25
25,26,Captain America: The First Avenger,2011,"Action, Adventure, Sci-Fi",124,PG-13,6.9,764786,176650000,Joe Johnston,"Joe Johnston,Chris Evans,Hugo Weaving,Samuel L...","Steve Rogers, a rejected military soldier, tra...","With plenty of pulpy action, a pleasantly retr...",80,273,74,100000,MARVEL,26
26,27,Ghost Rider: Spirit of Vengeance,2011,"Action, Fantasy, Thriller",96,PG-13,4.3,112898,51770000,Mark Neveldine,"Brian Taylor,Nicolas Cage,Ciarán Hinds,Idris E...","Johnny Blaze, tortured by the Ghost Rider's cu...","With a weak script, uneven CG work, and a Nic ...",18,114,31,100000,MARVEL,27
27,28,The Avengers,2012,"Action, Adventure, Sci-Fi",143,PG-13,8.0,1286985,623280000,Joss Whedon,"Joss Whedon,Robert Downey Jr.,Chris Evans,Scar...",Earth's mightiest heroes must come together an...,Thanks to a script that emphasizes its heroes'...,91,362,91,250000,MARVEL,28
28,29,The Amazing Spider-Man,2012,"Action, Adventure, Fantasy",136,PG-13,6.9,569274,262030000,Marc Webb,"Marc Webb,Andrew Garfield,Emma Stone,Rhys Ifan...",After Peter Parker is bitten by a genetically ...,A well-chosen cast and sure-handed direction a...,72,334,77,250000,MARVEL,29
29,30,Iron Man Three,2013,"Action, Adventure, Sci-Fi",130,PG-13,7.1,775425,409010000,Shane Black,"Shane Black,Robert Downey Jr.,Guy Pearce,Gwyne...",When Tony Stark's world is torn apart by a for...,"With the help of its charismatic lead, some im...",79,328,78,250000,MARVEL,30
30,31,The Wolverine,2013,"Action, Sci-Fi",126,PG-13,6.7,437712,132560000,James Mangold,"James Mangold,Hugh Jackman,Will Yun Lee,Tao Ok...",Wolverine comes to Japan to meet an old friend...,Although its final act succumbs to the usual c...,71,258,69,250000,MARVEL,31
31,32,Thor: The Dark World,2013,"Action, Adventure, Fantasy",112,PG-13,6.9,614115,206360000,Alan Taylor,"Alan Taylor,Chris Hemsworth,Natalie Portman,To...",When the Dark Elves attempt to plunge the univ...,It may not be the finest film to come from the...,66,284,75,250000,MARVEL,32
32,33,Captain America: The Winter Soldier,2014,"Action, Adventure, Sci-Fi",136,PG-13,7.7,759721,259770000,Anthony Russo,"Joe Russo,Chris Evans,Samuel L. Jackson,Scarle...",As Steve Rogers struggles to embrace his role ...,"Suspenseful and politically astute, Captain Am...",90,306,92,250000,MARVEL,33
33,34,The Amazing Spider-Man 2,2014,"Action, Adventure, Fantasy",142,PG-13,6.6,425691,202850000,Marc Webb,"Marc Webb,Andrew Garfield,Emma Stone,Jamie Fox...","When New York is put under siege by Oscorp, it...",While the cast is outstanding and the special ...,51,309,64,100000,MARVEL,34
34,35,X-Men: Days of Future Past,2014,"Action, Adventure, Sci-Fi",132,PG-13,7.9,671146,233920000,Bryan Singer,"Bryan Singer,Patrick Stewart,Ian McKellen,Hugh...",The X-Men send Wolverine to the past in a desp...,X-Men: Days of Future Past combines the best e...,90,329,91,250000,MARVEL,35
35,36,Guardians of the Galaxy,2014,"Action, Adventure, Comedy",121,PG-13,8.0,1069895,333180000,James Gunn,"James Gunn,Chris Pratt,Vin Diesel,Bradley Coop...",A group of intergalactic criminals must pull t...,Guardians of the Galaxy is just as irreverent ...,92,332,92,250000,MARVEL,36
36,37,Avengers: Age of Ultron,2015,"Action, Adventure, Sci-Fi",141,PG-13,7.3,772476,459010000,Joss Whedon,"Joss Whedon,Robert Downey Jr.,Chris Evans,Mark...",When Tony Stark and Bruce Banner try to jump-s...,"Exuberant and eye-popping, Avengers: Age of Ul...",76,372,83,250000,MARVEL,37
37,38,Ant-Man,2015,"Action, Adventure, Comedy",117,PG-13,7.3,590834,180200000,Peyton Reed,"Peyton Reed,Paul Rudd,Michael Douglas,Corey St...",Armed with a super-suit with the astonishing a...,"Led by a charming performance from Paul Rudd, ...",83,334,86,100000,MARVEL,38
38,39,Fantastic Four,2015,"Action, Adventure, Sci-Fi",100,PG-13,4.2,155942,56120000,Josh Trank,"Josh Trank,Miles Teller,Kate Mara,Michael B. J...",Four young outsiders teleport to an alternate ...,"Dull and downbeat, this Fantastic Four proves ...",9,260,18,100000,MARVEL,39
39,40,Deadpool,2016,"Action, Adventure, Comedy",108,R,8.0,927737,363070000,Tim Miller,"Tim Miller,Ryan Reynolds,Morena Baccarin,T.J. ...",A wisecracking mercenary gets experimented on ...,"Fast, funny, and gleefully profane, the fourth...",85,347,90,100000,MARVEL,40
40,41,Captain America: Civil War,2016,"Action, Adventure, Sci-Fi",147,PG-13,7.8,689763,408080000,Anthony Russo,"Joe Russo,Chris Evans,Robert Downey Jr.,Scarle...",Political involvement in the Avengers' affairs...,Captain America: Civil War begins the next wav...,90,421,89,100000,MARVEL,41
41,42,X-Men: Apocalypse,2016,"Action, Adventure, Sci-Fi",144,PG-13,6.9,402935,155440000,Bryan Singer,"Bryan Singer,James McAvoy,Michael Fassbender,J...",In the 1980s the X-Men must defeat an ancient ...,Overloaded action and a cliched villain take t...,47,343,65,100000,MARVEL,42
42,43,Doctor Strange,2016,"Action, Adventure, Fantasy",115,PG-13,7.5,623361,232640000,Scott Derrickson,"Scott Derrickson,Benedict Cumberbatch,Chiwetel...",While on a journey of physical and spiritual h...,Doctor Strange artfully balances its outré sou...,89,382,85,100000,MARVEL,43
43,44,Logan,2017,"Action, Drama, Sci-Fi",137,R,8.1,670710,226280000,James Mangold,"James Mangold,Hugh Jackman,Patrick Stewart,Daf...","In a future where mutants are nearly extinct, ...",Hugh Jackman makes the most of his final outin...,93,420,90,50000,MARVEL,44
44,45,Guardians of the Galaxy Vol. 2,2017,"Action, Adventure, Comedy",136,PG-13,7.6,592260,389810000,James Gunn,"James Gunn,Chris Pratt,Zoe Saldana,Dave Bautis...",The Guardians struggle to keep together as a t...,Guardians of the Galaxy Vol. 2's action-packed...,85,421,87,100000,MARVEL,45
45,46,Spider-Man: Homecoming,2017,"Action, Adventure, Sci-Fi",133,PG-13,7.4,536012,334200000,Jon Watts,"Jon Watts,Tom Holland,Michael Keaton,Robert Do...",Peter Parker balances his life as an ordinary ...,Spider-Man: Homecoming does whatever a second ...,92,393,87,100000,MARVEL,46
46,47,Thor: Ragnarok,2017,"Action, Adventure, Comedy",130,PG-13,7.9,620623,315060000,Taika Waititi,"Taika Waititi,Chris Hemsworth,Tom Hiddleston,C...","Imprisoned on the planet Sakaar, Thor must rac...","Exciting, funny, and above all fun, Thor: Ragn...",93,434,87,50000,MARVEL,47
47,48,Black Panther,2018,"Action, Adventure, Sci-Fi",134,PG-13,7.3,655779,700060000,Ryan Coogler,"Ryan Coogler,Chadwick Boseman,Michael B. Jorda...","T'Challa, heir to the hidden but advanced king...",Black Panther elevates superhero cinema to thr...,96,523,79,50000,MARVEL,48
48,49,Avengers: Infinity War,2018,"Action, Adventure, Sci-Fi",149,PG-13,8.4,888104,678820000,Anthony Russo,"Joe Russo,Robert Downey Jr.,Chris Hemsworth,Ma...",The Avengers and their allies must be willing ...,Avengers: Infinity War ably juggles a dizzying...,85,480,91,50000,MARVEL,49
49,50,Deadpool 2,2018,"Action, Adventure, Comedy",119,R,7.7,501971,324590000,David Leitch,"David Leitch,Ryan Reynolds,Josh Brolin,Morena ...",Foul-mouthed mutant mercenary Wade Wilson (a.k...,Though it threatens to buckle under the weight...,84,419,85,25000,MARVEL,50
50,51,Ant-Man and the Wasp,2018,"Action, Adventure, Comedy",118,PG-13,7.0,329600,216650000,Peyton Reed,"Peyton Reed,Paul Rudd,Evangeline Lilly,Michael...",As Scott Lang balances being both a superhero ...,"A lighter, brighter superhero movie powered by...",87,435,75,25000,MARVEL,51
51,52,Venom,2018,"Action, Adventure, Sci-Fi",112,PG-13,6.7,383743,213520000,Ruben Fleischer,"Ruben Fleischer,Tom Hardy,Michelle Williams,Ri...",A failed reporter is bonded to an alien entity...,Venom's first standalone movie turns out to be...,29,354,81,25000,MARVEL,52
52,53,Captain Marvel,2019,"Action, Adventure, Sci-Fi",123,PG-13,6.8,473437,426830000,Anna Boden,"Anna Boden,Brie Larson,Samuel L. Jackson,Ben M...",Carol Danvers becomes one of the universe's mo...,"Packed with action, humor, and visual thrills,...",79,537,45,100000,MARVEL,53
53,54,Avengers: Endgame,2019,"Action, Adventure, Drama",181,PG-13,8.4,890937,858370000,Anthony Russo,"Joe Russo,Robert Downey Jr.,Chris Evans,Mark R...",After the devastating events of Avengers: Infi...,"Exciting, entertaining, and emotionally impact...",94,541,90,50000,MARVEL,54
54,55,X-Men: Dark Phoenix,2019,"Action, Adventure, Sci-Fi",113,PG-13,5.7,164427,65850000,Simon Kinberg,"Simon Kinberg,James McAvoy,Michael Fassbender,...",Jean Grey begins to develop incredible powers ...,Dark Phoenix ends an era of the X-Men franchis...,22,379,64,10000,MARVEL,55
55,56,Spider-Man: Far from Home,2019,"Action, Adventure, Sci-Fi",129,PG-13,7.5,353385,390530000,Jon Watts,"Jon Watts,Tom Holland,Samuel L. Jackson,Jake G...",Following the events of Avengers: Endgame (201...,A breezily unpredictable blend of teen romance...,90,449,95,50000,MARVEL,56
56,57,The New Mutants,2020,"Action, Horror, Mystery",94,PG-13,5.3,59535,0,Josh Boone,"Josh Boone,Maisie Williams,Anya Taylor-Joy,Cha...","Five young mutants, just discovering their abi...",Rendering a list of potentially explosive ingr...,35,126,56,2500,MARVEL,57
57,58,Superman and the Mole-Men,1951,"Action, Adventure, Drama",58,Passed,5.7,1828,0,Lee Sholem,"George Reeves,Phyllis Coates,Jeff Corey,Walter...",When underground beings explore the surface wo...,"Even at under an hour, this children's fantasy...",0,2,83,250,DC,58
58,59,Batman: The Movie,1966,"Adventure, Comedy, Crime",105,PG,6.5,30289,0,Leslie H. Martinson,"Adam West,Burt Ward,Lee Meriwether,Cesar Romero",The Dynamic Duo faces four supervillains who p...,Batman: The Movie elevates camp to an art form...,79,33,62,100000,DC,59
59,60,Superman,1978,"Action, Adventure, Drama",143,PG,7.3,162395,134220000,Richard Donner,"Christopher Reeve,Margot Kidder,Gene Hackman,M...",An alien orphan is sent from his dying planet ...,"Superman deftly blends humor and gravitas, tak...",94,68,86,250000,DC,60
60,61,Superman II,1980,"Action, Adventure, Sci-Fi",127,PG,6.8,100030,108190000,Richard Lester,"Gene Hackman,Christopher Reeve,Margot Kidder,N...",Superman agrees to sacrifice his powers to sta...,The humor occasionally stumbles into slapstick...,86,51,76,100000,DC,61
61,62,Swamp Thing,1982,"Horror, Sci-Fi",91,PG,5.4,13328,0,Wes Craven,"Louis Jourdan,Adrienne Barbeau,Ray Wise,David ...",After a violent incident with a special chemic...,Unabashedly campy -- often to its detriment --...,63,38,40,10000,DC,62
62,63,Superman III,1983,"Action, Adventure, Comedy",125,PG,5.0,65340,59950000,Richard Lester,"Christopher Reeve,Richard Pryor,Margot Kidder,...",Synthetic kryptonite laced with tar splits Sup...,"When not overusing sight gags, slapstick, and ...",30,53,23,100000,DC,63
63,64,Supergirl,1984,"Action, Adventure, Fantasy",124,PG,4.4,19361,13600000,Jeannot Szwarc,"Helen Slater,Faye Dunaway,Peter O'Toole,Mia Fa...","After losing a powerful orb, Kara Zor-El, Supe...",The effects are cheesy and Supergirl's wide-ey...,9,32,26,25000,DC,64
64,65,Superman IV: The Quest for Peace,1987,"Action, Adventure, Sci-Fi",90,PG,3.7,44082,15680000,Sidney J. Furie,"Christopher Reeve,Gene Hackman,Margot Kidder,J...",The Man of Steel crusades for nuclear disarmam...,The Superman series bottoms out here: the acti...,11,45,16,50000,DC,65
65,66,The Return of Swamp Thing,1989,"Action, Adventure, Comedy",88,PG-13,4.6,4454,190000,Jim Wynorski,"Dick Durock,Heather Locklear,Louis Jourdan,Sar...","In this tongue-in-cheek sequel, the benevolent...",A mad scientist's (Louis Jourdan) vegetarian s...,44,9,55,2500,DC,66
66,67,Batman,1989,"Action, Adventure",126,PG-13,7.5,344868,251190000,Tim Burton,"Michael Keaton,Jack Nicholson,Kim Basinger,Rob...",The Dark Knight of Gotham City begins his war ...,"An eerie, haunting spectacle, Batman succeeds ...",71,76,84,250000,DC,67
67,68,Batman Returns,1992,"Action, Crime, Fantasy",126,PG-13,7.0,279545,162830000,Tim Burton,"Michael Keaton,Danny DeVito,Michelle Pfeiffer,...",While Batman deals with a deformed man calling...,"Director Tim Burton's dark, brooding atmospher...",80,84,73,250000,DC,68
68,69,Batman Forever,1995,"Action, Adventure",121,PG-13,5.4,238230,184030000,Joel Schumacher,"Val Kilmer,Tommy Lee Jones,Jim Carrey,Nicole K...",Batman must battle former district attorney Ha...,"Loud, excessively busy, and often boring, Batm...",38,68,32,250000,DC,69
69,70,Batman & Robin,1997,"Action, Sci-Fi",125,PG-13,3.8,237759,107330000,Joel Schumacher,"Arnold Schwarzenegger,George Clooney,Chris O'D...",Batman and Robin try to keep their relationshi...,Joel Schumacher's tongue-in-cheek attitude hit...,12,93,16,250000,DC,70
70,71,Steel,1997,"Action, Adventure, Crime",97,PG-13,2.9,11519,1710000,Kenneth Johnson,"Shaquille O'Neal,Annabeth Gish,Judd Nelson,Ric...",A scientist for the military turns himself int...,Steel is a badly-acted movie that indulges not...,12,26,15,5000,DC,71
71,72,Catwoman,2004,"Action, Crime, Fantasy",104,PG-13,3.4,112972,40200000,Pitof,"Halle Berry,Sharon Stone,Benjamin Bratt,Lamber...","A shy woman, endowed with the speed, reflexes,...","Halle Berry is the lone bright spot, but even ...",9,198,18,250000,DC,72

# **Q1**
- How many of the movies in the original table were released during or after
2000 (“year”)?

In [ ]:
befr_2000 = df[df['year']< 2000]
during_2000 = df[df['year'] == 2000]
aftr_2000 = df[df["year"]>2000]
print("number of movies released after 2000 is  ",aftr_2000.shape[0])
print("number of movies released before 2000 is  ",befr_2000.shape[0])
print("number of movies released during 2000 is  ",during_2000.shape[0])

number of movies released after 2000 is   72
number of movies released before 2000 is   17
number of movies released during 2000 is   1

# **Q2**
- How many movies did DC release during or after 2000? How many movies
did Marvel release during or after 2000?

In [ ]:
dc_aftr_2000 = df[df['entity'] == 'DC']
after_number =dc_aftr_2000[dc_aftr_2000['year']>2000].shape[0]
during_numbr = dc_aftr_2000[dc_aftr_2000['year']==2000].shape[0]
print("Dc released movies after 2000 are ",after_number)
print("Dc released movies during 2000 are ",during_numbr)

Dc released movies after 2000 are  19
Dc released movies during 2000 are  0

# **Q3**
- . Does DC or Marvel have the highest average rating on IMDB
(“imdb_rating”)

In [ ]:

print("DC avg rating",round(df[df['entity'] == 'DC']["imdb_rating"].sum()/len(df[df['entity'] == 'DC']["imdb_rating"]),3))
print("Marvel avg rating ",round(df[df['entity'] == 'MARVEL']["imdb_rating"].sum()/len(df[df['entity'] == 'MARVEL']["imdb_rating"]),3))

DC avg rating 6.133
Marvel avg rating  6.795

# **Q4** 
- Was the lowest rated movie on IMDB (“imdb_rating”) a DC or a Marvel
movie?

In [ ]:
df[df['imdb_rating'] == df['imdb_rating'].min()]

,Unnamed: 0,title,year,genre,runtime,mpa_rating,imdb_rating,imdb_votes,imdb_gross,director,stars,description,crit_consensus,tomato_meter,tomato_review,tom_aud_score,tom_ratings,entity,id
70,71,Steel,1997,"Action, Adventure, Crime",97,PG-13,2.9,11519,1710000,Kenneth Johnson,"Shaquille O'Neal,Annabeth Gish,Judd Nelson,Ric...",A scientist for the military turns himself int...,Steel is a badly-acted movie that indulges not...,12,26,15,5000,DC,71

# **Q5** 
- Was the highest rated movie on IMDB (“imdb_rating”) a DC or a Marvel
movie?

In [ ]:
df[df['imdb_rating'] == df['imdb_rating'].max()]

,Unnamed: 0,title,year,genre,runtime,mpa_rating,imdb_rating,imdb_votes,imdb_gross,director,stars,description,crit_consensus,tomato_meter,tomato_review,tom_aud_score,tom_ratings,entity,id
75,76,The Dark Knight,2008,"Action, Crime, Drama",152,PG-13,9.0,2369304,534860000,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",When the menace known as the Joker wreaks havo...,"Dark, complex, and unforgettable, The Dark Kni...",94,344,94,250000,DC,76

# **Q6**
- Does DC or Marvel have the highest average critic’s rating on Rotten
Tomatoes (“tomato_meter”)?

In [ ]:
print("DC avg rating on rotten tomatoes",df[df['entity'] == 'DC']["tomato_meter"].sum()/len(df[df['entity'] == 'DC']))
print("Marvel avg rating rotten tomatoes",df[df['entity'] == 'MARVEL']["tomato_meter"].sum()/len(df[df['entity'] == 'MARVEL']))

DC avg rating on rotten tomatoes 52.45454545454545
Marvel avg rating rotten tomatoes 64.21052631578948

# **Q7**
- Does DC or Marvel have the highest average audience rating on Rotten
Tomatoes (“tom_aud_score”)?

In [ ]:
print("DC highest avg audience rating on rotten tomatoes",df[df['entity'] == 'DC']["tom_aud_score"].sum()/len(df[df['entity'] == 'DC']))
print("Marvel highest avg audience rating rotten tomatoes",df[df['entity'] == 'MARVEL']["tom_aud_score"].sum()/len(df[df['entity'] == 'MARVEL']))

DC highest avg audience rating on rotten tomatoes 60.484848484848484
Marvel highest avg audience rating rotten tomatoes 70.35087719298245

# **Q8**
- Which movie had the largest difference between the critic’s score
(“tomato_meter”) and audience score (“tom_aud_score”) on Rotten Tomatoes in which
the audience score was higher than the critic’s score?

In [ ]:
d = df[df['tom_aud_score'] ==df['tom_aud_score'].max() ]
d[["title",'tom_aud_score', "tomato_meter"]]

                        title  tom_aud_score  tomato_meter
55  Spider-Man: Far from Home             95            90

# **Q9**
-  Which movie had the largest difference between the critic’s score
(“tomato_meter”) and audience score (“tom_aud_score”) on Rotten Tomatoes in which
the audience score was lower than the critic’s score?

In [ ]:
d = df[df['tomato_meter'] ==df['tomato_meter'].max() ]
d[["title",'tom_aud_score', "tomato_meter"]]

            title  tom_aud_score  tomato_meter
47  Black Panther             79            96

# **Q10**
- From the movies included in the database and those released during or
after 2000, did DC or Marvel have the highest total gross earnings (“imdb_gross”)?

In [ ]:
# in total movies
df[df['imdb_gross'] == df['imdb_gross'].max()][['year','title','imdb_gross','entity']]

    year              title  imdb_gross  entity
53  2019  Avengers: Endgame   858370000  MARVEL

In [ ]:
#after 2000
y = df[df['year'] >2000]
y[y['imdb_gross'] == y['imdb_gross'].max()][['year','title','imdb_gross','entity']]

    year              title  imdb_gross  entity
53  2019  Avengers: Endgame   858370000  MARVEL

In [ ]:
#during 2000
d = df[df['year'] ==2000]
d[d['imdb_gross'] == d['imdb_gross'].max()][["year","title",'imdb_gross','entity']]

   year  title  imdb_gross  entity
3  2000  X-Men   157300000  MARVEL

# **Q11**
- From the movies included in the database and those released during or
after 2000, did DC or Marvel have the highest earning movie and what was the movie
(“imdb_gross”)?

In [ ]:
d = df[df['year'] ==2000]

d[d['imdb_gross'] == d['imdb_gross'].max()][['title','imdb_gross']]

   title  imdb_gross
3  X-Men   157300000

In [ ]:
y = df[df['year'] >2000]
y[y['imdb_gross'] == y['imdb_gross'].max()][['year','title','imdb_gross']]

    year              title  imdb_gross
53  2019  Avengers: Endgame   858370000

In [ ]:
df[df['imdb_gross'] == df['imdb_gross'].max()][["year",'title','imdb_gross']]

    year              title  imdb_gross
53  2019  Avengers: Endgame   858370000

# **Q12**
-  Does DC or Marvel movies have a longer average runtime (“runtime”)?

In [ ]:
df[df['runtime'] == df['runtime'].max()]

,Unnamed: 0,title,year,genre,runtime,mpa_rating,imdb_rating,imdb_votes,imdb_gross,director,stars,description,crit_consensus,tomato_meter,tomato_review,tom_aud_score,tom_ratings,entity,id,movies_diff
0,1,Captain America,1944,"Action, Adventure, Sci-Fi",244,Approved,5.5,844,0,Elmer Clifton,"Elmer Clifton,Dick Purcell,Lorna Gray,Lionel A...",Superhero Captain America battles the evil for...,"Find one of these old serials, friend. They're...",0,1,82,250,MARVEL,1,-82

# **Q13**
-  Does DC or Marvel have the larger total runtime for all movies released
during or after 2000 (“runtime”)?

In [ ]:
# in all movies
print("DC run timerun in all movies ",df[df['entity'] == 'DC'].runtime.max() )
print("MARVEL run timerun in all movies ",df[df['entity'] == 'MARVEL'].runtime.max() )

DC run timerun in all movies  164
MARVEL run timerun in all movies  244

In [ ]:
# during and after 2000
d_af = df[df['year']>=2000]
print("DC run timerun in  movies ",d_af[d_af['entity'] == 'DC'].runtime.max() )
print("MARVEL run timerun in movies ",d_af[d_af['entity'] == 'MARVEL'].runtime.max() )

DC run timerun in  movies  164
MARVEL run timerun in movies  181

# **Q14**
- Calculate the gross earnings per runtime for DC and Marvel (total gross
earnings (“imdb_gross”) divided by total runtime (“runtime”)). Does DC or Marvel
have the highest gross earnings per unit runtime?

In [ ]:

df['gross_earning']= df['imdb_gross']/df['runtime']
df[df['gross_earning'] == df['gross_earning'].max()]

,Unnamed: 0,title,year,genre,runtime,mpa_rating,imdb_rating,imdb_votes,imdb_gross,director,stars,description,crit_consensus,tomato_meter,tomato_review,tom_aud_score,tom_ratings,entity,id,movies_diff,gross_earning
47,48,Black Panther,2018,"Action, Adventure, Sci-Fi",134,PG-13,7.3,655779,700060000,Ryan Coogler,"Ryan Coogler,Chadwick Boseman,Michael B. Jorda...","T'Challa, heir to the hidden but advanced king...",Black Panther elevates superhero cinema to thr...,96,523,79,50000,MARVEL,48,17,5.224328e+06

# **Q15**
-  Does Marvel of DC have a higher percentage of movies with a PG-13
rating vs. all other ratings (“mpa_rating”)?

In [ ]:
# in PG-13
pg= df[df['mpa_rating'] == 'PG-13']
dc = pg[pg['entity']=='DC'].shape[0]
mar =pg[pg['entity']=='MARVEL'].shape[0]

dc_per = 100*dc/len(pg)
mar_per = 100*mar/len(pg)

print("in PG-13 the percentage of DC is {} and MARVEL is {}".format(dc_per,mar_per))

in PG-13 the percentage of DC is 31.34328358208955 and MARVEL is 68.65671641791045

In [ ]:
# in other
other = df[df['mpa_rating'] != 'PG-13']
dc = other[other['entity']=='DC'].shape[0]
mar =other[other['entity']=='MARVEL'].shape[0]

dc_per = dc/len(pg)*100
mar_per = mar/len(pg)*100
print("in PG-13 the percentage of DC is {} and MARVEL is {}".format(dc_per,mar_per))

in PG-13 the percentage of DC is 17.91044776119403 and MARVEL is 16.417910447761194